version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt

  build:
    commands:
      - echo "Building the SAM application..."
      - sam build

  post_build:
    commands:
      - echo "Packaging the SAM application..."
      - sam package --output-template-file packaged.yaml --s3-bucket goresumebucket
      - echo "Deploying the SAM application..."
      - sam deploy --template-file packaged.yaml --stack-name cloudstack --capabilities CAPABILITY_IAM

artifacts:
  files:
    - '**/*'

