version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - sam build
  post_build:
    commands:
      - sam package --output-template-file packaged.yaml --s3-bucket goresumebucket
      - sam deploy --template-file packaged.yaml --stack-name cloudstack --capabilities CAPABILITY_IAM
