AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >
  SAM Template for deploying a Lambda function with API Gateway and DynamoDB

Resources:
  CloudCounter:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: 'CloudCounter'
      AttributeDefinitions:
        - AttributeName: 'id'
          AttributeType: 'N'
      KeySchema:
        - AttributeName: 'id'
          KeyType: 'HASH'
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  CountFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://goresumebucket/Lambda.zip
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      Policies:
        - AWSLambdaDynamoDBPolicy:
            TableName: !Ref CloudCounter
      Environment:
        Variables:
          TableName: !Ref CloudCounter
      Events:
        IncrementEndpoint:
          Type: HttpApi
          Properties:
            Path: /increment
            Method: GET

  MyHttpApi:
    Type: 'AWS::Serverless::HttpApi'
    Properties:
      StageName: Prod

Outputs:
  ApiUrl:
    Description: 'API Gateway endpoint URL for the Lambda function'
    Value: !Sub 'https://${MyHttpApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/increment'

  LambdaFunctionArn:
    Description: 'ARN of the Lambda function'
    Value: !GetAtt CountFunction.Arn
